# ----------------------------------------------------------------------------
#
# Package             : <package name>
# Source Repo         : <orginal repo link>
# Travis Job Link     : <travis job link>
# Created travis.yml  : <Yes, if travis.yml is created. No, if existing travis.yml is modified.>
# Maintainer          : <your name and email id>
#
# Script License      : Apache License, Version 2 or later
#
# ---

language: cpp

compiler:
  - gcc
  - clang

arch:
  - amd64
  - ppc64le

addons:
    apt:
        update: true
        packages:
      `     - texlive
            - texlive-extra-utils
            - texlive-latex-extra
            - libxml2-utils
            - cmake cmake-data
            - flex
            - bison
            - qt5-default

script:
    - mkdir build
    - cd build
    - cmake -G "Unix Makefiles" -Dbuild_doc=ON -Dbuild_wizard=ON ..
    - make
    - make tests
